### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by thany** [glencoesoftware/jxrlib#17]
Please release binaries 🙏

I'm sure you (author) tests whether the source code can build or not, so why not make the result of that available to everyone? I personally don't have build tools on my pc, just like many other people who just need this lib as a plugin for something.

**Comment by joshmoore** [comment]
Hi @thany. Can you try the jar from https://ci.appveyor.com/project/gs-jenkins/jxrlib/build/artifacts ?

**Comment by thany** [comment]
That looks to be some library for Java bindings.

I actually already went ahead and built binaries myself using the free Visual Studio. It's quite a journey to get there, but I do now have executabales. If you want them as well, here they are:
[JXREncoderDecoder-x64.zip](https://github.com/glencoesoftware/jxrlib/files/2097194/JXREncoderDecoder-x64.zip)
[JXREncoderDecoder-x86.zip](https://github.com/glencoesoftware/jxrlib/files/2097195/JXREncoderDecoder-x86.zip)

I'm not sure how well I did compiling them. VS complained about the 2012 toolkit not being available, so I "upgraded" the projects to 2015. Not sure what consequences that'll have, but they work on my machine, so maybe/hopefully they work on others' machines too.

**Comment by mloskot** [comment]
jxrlib is packaged for https://github.com/Microsoft/vcpkg which builds from source w/o any hassle, and allows integration with VS2017 or CMake.

IMHO, there is little point in providing Windows/Visual Studio-compatible binaries of the library.

----

Note, the vcpkg is pulled from alternative jxrlib mirror https://github.com/4creators/jxrlib based on the original CodePlex-hosted jxrlib.
This makes me wonder, how much if at all glencoesoftware/jxrlib diverged from the original implementation of jxrlib. If it does, perhaps it should be renamed differently, eg. `glencoejxrlib`, to avoid confusing users. When I run `apt-get install jxrlib` users may rightly expect it to be the original Microsoft's implementation. While, on ArchLinux AUR the package https://aur.archlinux.org/packages/jxrlib-git/ has already switched to https://github.com/glencoesoftware/jxrlib.git This just cultivates quite the mess after Microsoft abandoned the jxrlib.

**Comment by melissalinkert** [comment]
Thank you for bringing this issue to our attention, @thany and @mloskot.  The purpose of this repository was to provide a Java wrapper for the original jxrlib C library, primarily for use in Bio-Formats (https://github.com/openmicroscopy/bioformats).  It was never our intention for this repository to be the authoritative version of jxrlib, which is why we do not provide separate binaries and are not able to support usage outside of Bio-Formats.  We would be open to renaming the repository if that reduces confusion.

As @joshmoore mentions, a Java jar containing the Java wrapper we have added plus binaries built via CI is available.  The current version is 0.2.1 and can be downloaded here: http://artifacts.openmicroscopy.org/artifactory/simple/ome.releases/ome/jxrlib-all/0.2.1/

We are working on adding additional documentation to this repository to clarify the history and scope of changes and expect to have a README pushed soon.  In general, the commits here add a Java wrapper, tests, cross-platform build support, and C API to facilitate working with JPEG-XR data in memory.  https://github.com/glencoesoftware/jxrlib/commit/e922fa50cdf9a58f40cad07553bcaa2883d3c5bf was the last commit from the original CodePlex import, so everything on master from https://github.com/glencoesoftware/jxrlib/commit/3cba09748a496bbe3514e38b51b4936380756300 onwards diverges.

**Comment by mloskot** [comment]
@melissalinkert Thank you for the explanation, it's much appreciated.

**Comment by thany** [comment]
@melissalinkert The binaries provided in the jar are libraries specific to java in some way. I don't know how it works in java, but they are not the two exe files needed to use jxrlib separately. That's why I built them myself.
